### ISSUE TITLE
error converting file

### ISSUE THREAD

**Issue by baditaflorin** [vibrog/osm-routelist#3]
mapuser@map-analyst:/data/files/florinb/osm-routelist$ osmosis --rb romania.osm.pbf --tf accept-relations type=route --tf reject-relations route=road --tf reject-relations route=junction --tf reject-relations route=detour  --tf reject-relations route=power --tf reject-ways --tf reject-nodes --wx routes.osm
Jul 16, 2015 3:54:30 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.43.1
Jul 16, 2015 3:54:30 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Jul 16, 2015 3:54:30 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
Jul 16, 2015 3:54:30 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
Jul 16, 2015 3:54:30 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-rb failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to process PBF stream
        at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.openstreetmap.osmosis.osmbinary.file.FileFormatException: Unexpectedly long header 65536 bytes. Possibly corrupt file.
        at org.openstreetmap.osmosis.osmbinary.file.FileBlockHead.readHead(FileBlockHead.java:50)
        at org.openstreetmap.osmosis.osmbinary.file.FileBlock.process(FileBlock.java:130)
        at org.openstreetmap.osmosis.osmbinary.file.BlockInputStream.process(BlockInputStream.java:34)
        at crosby.binary.osmosis.OsmosisReader.run(OsmosisReader.java:45)
        ... 1 more

Jul 16, 2015 3:54:30 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:328)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:31)

**Comment by baditaflorin** [comment]
now is working, something was wrong with the wget command
